name: "deploy"

on:
  schedule:
    - cron: "0 11 * * 0" # 毎週日曜日20時に実行(JST)
    # - cron: "0 11 * * *" # 毎日20時に実行(JST)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    description: 'Deploy to production'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.HOOKS_URL }}
          method: "POST"
