name: "scraping"

on:
  schedule:
    - cron: "0 10 * * 0" # 毎週日曜日19時に実行(JST)
    # - cron: "0 10 * * *" # 毎日19時に実行(JST)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      year:
        description: 'Year to scraping syllabus for'
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run
        run: |
          YEAR=${{ github.event.inputs.year }} docker compose up

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data"

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master
