name: "scraping"

on:
  schedule:
    - cron: "0 10 * * 0" # 毎週日曜日19時に実行(JST)
    # - cron: "0 10 * * *" # 毎日19時に実行(JST)
  workflow_dispatch:
    inputs:
      year:
        description: 'Year to scraping syllabus for'
        required: true
        type: number

jobs:
  job:
    name: build-and-deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Set year
        id: set-year
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "YEAR=${{ github.event.inputs.year }}" >> $GITHUB_ENV
          else
            echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          fi

      - name: Run
        run: |
          YEAR=${{ env.YEAR }} docker compose up

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data"

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master

      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: Scraping-${{ env.CURRENT_DATETIME }}
          FILE: data/${{ env.YEAR }}.json
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.FILE }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.HOOKS_URL }}
          method: "POST"
