name: "scraping"

on:
  schedule:
    - cron: "0 10 * * 0" # 毎週日曜日19時に実行(JST)
    # - cron: "0 10 * * *" # 毎日19時に実行(JST)
  workflow_dispatch:
    inputs:
      year:
        description: 'Year to scrape syllabus for'
        required: true
        type: number

jobs:
  scraping:
    name: scraping
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date and calculate fiscal year
        env:
          TZ: "Asia/Tokyo"
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          CURRENT_YEAR=$(date +'%Y')
          CURRENT_MONTH=$(date +'%m')
          if [ "$CURRENT_MONTH" -lt 4 ]; then
            FISCAL_YEAR=$((CURRENT_YEAR - 1))
          else
            FISCAL_YEAR=$CURRENT_YEAR
          fi
          echo "CURRENT_DATE=$CURRENT_DATE" >> $GITHUB_ENV
          echo "FISCAL_YEAR=$FISCAL_YEAR" >> $GITHUB_ENV

      - name: Set year from inputs or calculated fiscal year
        id: set-year
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "YEAR=${{ github.event.inputs.year }}" >> $GITHUB_ENV
          else
            echo "YEAR=${{ env.FISCAL_YEAR }}" >> $GITHUB_ENV
          fi

      - name: Run
        run: YEAR=${{ env.YEAR }} docker compose up

      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: syllabus-${{ env.CURRENT_DATE }}
          FILE: data/${{ env.YEAR }}.json
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.FILE }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: data

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scraping

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deploy to Cloudflare pages
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.HOOKS_URL }}
          method: "POST"
